python3 main.py --dataset isaid \
    --min_image_size 512 \
    --max_image_size 512 \
    --pretext_task jigsaw-continuous \
    --pretext_task_ratio 0.5 \
    --backbone_pretrained t \
    --backbone_freeze f \
    --gpus '2' \
    --strategy "none" \
    --precision 32 \
    --batch_size 128 \
    --max_epochs 10 \
    --loss_only_for_transformed t